version: '3.8'

services:
  web:
    image: node:20
    container_name: express-mongoose-app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydatabase"
    
    command: sh -c "npm install && npm start"

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
